# before_install:
#   - gem install -v 2.0.2 bundler --no-rdoc --no-ri
#   - bundle _2.0.2_ install
services:
  - postgresql
addons:
  postgresql: '9.6'
before_script:
  - psql -c 'create database pgapp_test;' -U postgres
language: ruby
rvm:
  - 2.5.0
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: RZxWyXDaA1Uybv2tU8JcgaqsD8a6dUrEcA19t8KwLboKdj+U8U1Gkl/7bx36Xg2kIj/3QZtuBU7ioZpvyOk7pSQCFan8298BPE55Amv01rbq7omf0BYA2AAq5j0bGiS8IBGfBmsospOTBVzIP+/+L9BAwdL5TX2jnYF2wTutlKzSmes6tPMV82ItQJtJy6bfoAJ4YYjSIh8lmxBs9dosRwd+CdTFCORWSO3/NP80ZJFz5P4/O8QcCSdpsXuDClWVRTUqvhdT2gsHEURM3flPNLb6ECPB4hBYa0LtljvrJxMsOLTtpWFE5XPixBl+9dHKvTOQR5lE2fseBUGzYr9hT1mJEH/8xzqJMY79bFVDvV54TgrmeSWJUxSZBGVajpwxDLPRi6Rn9D7AJXumW30m6Q8QkoVY4gE/8YXIoh4CevzWsUF7zCGCKnl2JbVA1uVNbYBFuzuRPUtaVRW5yZQ4hMVGiT6hPuJr+TEdPiJKmJVetM640peKN8iycFupNZyCnVwaCA7usY8+NCjiWTLEYcaYpJ5XmRqY/ondOCoVCEoaGXlROqp2DyWGrNe3t7DQ4QtM3AIoOnZKN48z6yXn24gLzlE8r9jXB6WLInuVkw9O83vGabSGNcyubGjGcTKCNzLa08ypgdEkM/XhbtmhJkH7nJNzdV7xwIaqHU90rJ0=
  app: acebook-fantastic-four
  on:
    repo: krisswiltshire30/acebook-fantastic-four
