services:
  - postgresql
addons:
  postgresql: '9.6'
before_script:
  - psql -c 'create database pgapp_test;' -U postgres
language: ruby
rvm:
  - 2.5.0
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
  secure: driCuQsbovmF4aCRC8ay93cN5zYUgPbOE+LTMaX1ZRmfjoECVnzaPz92dKjVLgFcGmptWFNwE+YymMQU0IDq3ZYV6tHshAnGaL7FHQeS+UgQcvWBNb1LQbAYyrf1uE8zZgDacFSLoYWtcE9DGR63rJQoWj72YkysdZaQ6PNDj40lzUGSvpzKV7pUbOm7vWmDxOPKkioMGY8O8oaT7BzTOlL03jK9dkOR948wnvNjkoF01bBlnKueomEvzKOyP/ds7ZGd6hLPRBKd9Cw8oMJxJT1fR0c0gu/WDCXkX/Jm9musckpB8C+HQzEP4qgrj9VkWJNpJ4XYA/68/KqlFXS3JPb+XwR5p1npD0JXWl249snMCKRo48lbHw0fcuHjdaBMy8EWff9DNvQHU13jnpAzNjjXg4ZcoKRapAprkTk3UT9UWhVygZY+ZR9TC1r9qMZMU9DhLJX83fwO54ffIT8iMcrNFiNbzHXvIbnAMipjaO/XwZ1i0M8dQpqRbJwqiMUGPqUH9zj2UAEYP0L6IOmOE3LYB+FgzhwFFwzh7uycWk1phH9GJT4feRYl7TTyu3KL96WxY4pWQjtVViZgh2Dug6RWEtEzBbr8uz5isNdZF8cMgzhti4Qr+xsW0MyQRkXback4r0F+X69qzi7ffbWhyxdG3aCwP76t+n09vI5YsVw=
  app: acebook-fantastic-four
  on:
    repo: krisswiltshire30/acebook-fantastic-four
  run: 'rake db:migrate'
